SMS/urls.py
from django.urls import path

from SMS import views

app_name = 'sms'
urlpatterns = [
    path('', views.index, name='index'),
    # path('update_news/<int:pk>',views.update_news,name='update_news'),
    # path('get_news_ajax/',views.get_news_ajax,name='get_news_ajax'),
    # path('update_news_download_number_ajax/',views.update_news_download_number_ajax,name='update_news_download_number_ajax'),
    # path('delete_news_ajax/',views.delete_news_ajax,name='delete_news_ajax'),
]

apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django.urls import include, path
from django.contrib import admin


from theme import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home),
    path('base_layout',views.base_layout,name='base_layout'),

    path('employee/',include('employee.urls',namespace='employee')),
    path('MinersTracking/',include('MinersTracking.urls',namespace='MinersTracking')),
    path('FireExp/',include('FireExp.urls',namespace='FireExp')),
    path('Controlling/',include('Controlling.urls',namespace='Controlling')),
    path('DGMS_Forms/',include('DGMS_Forms.urls',namespace='DGMS_Forms')),
    path('Strata/',include('Strata.urls',namespace='Strata')),
    path('theme/',include('theme.urls',namespace='theme')),


    path('accounts/', include('accounts.urls')),
    path('snippets/', include('snippets.urls')),
    path('gasmonitoring/', include('gasmonitoring.urls', namespace='gasmonitoring')),
    path('temp_monitoring/', include('temp_monitoring.urls', namespace='temp_monitoring')),
    path('gasmonitoring_wifi/', include('gasmonitoring_wifi.urls', namespace='gasmonitoring_wifi')),
    path('inventory_management/', include('inventory_management.urls', namespace='inventory_management')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('Training_Rescue_Accident/', include('Training_Rescue_Accident.urls', namespace='Training_Rescue_Accident')),
    path('ProductionMonitoring/', include('ProductionMonitoring.urls',namespace='ProductionMonitoring')),
    path('sensor/', include('sensor.urls', namespace='sensor')),### prasanjit dey(gas monitoring)
    path('water_level_monitoring/', include('water_level_monitoring.urls', namespace='water_level_monitoring')),### SS MISHRA(water monitoring)
    # path('tags_input/', include('tags_input.urls', namespace='tags_input')),
    path('sms/', include('SMS.urls', namespace='sms')),
    path('news/', include('news.urls', namespace='news')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('wm_test/', include('wm_test.urls', namespace='weather_monitoring')),
    path('setting/', include('setting.urls', namespace='setting')),
    path('Slope/', include('Slope.urls', namespace='Slope')),
    path('safety/', include('safety.urls', namespace='safety')),
    # path('',include('pwa.urls')),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'apps.views.error_404_view'

safety/urls.py
from django.urls import path
from safety import views 
from django.views.decorators.cache import  cache_page
app_name='safety'
urlpatterns=[
    path('',views.safe,name='safe'),
   # path('index',views.index),
    path('show/<int:pk>',views.show,name='show'),
    path('fetch_dropdownlist',views.fetch_dropdownlist,name='fetch_dropdownlist'),
    path('edit/<int:pk>',views.edit,name='edit'),
    path('manage',views.manage,name='manage'),
    path('delete/<int:pk>',views.delete,name='delete'),
            ]

safety/models.py
from django.db import models
from employee.models import MineDetails
class Safety(models.Model):
    objects=None
    mine=models.ForeignKey(MineDetails,on_delete=models.CASCADE,null=True,blank=True)
    owner=models.CharField(max_length=200)
    agent=models.CharField(max_length=200)
    manager=models.CharField(max_length=200)
    status_report=models.DateField()
    class Meta:
        db_table="safety"
        
        
        
class SafetyTable(models.Model):
    safety_id=models.ForeignKey(Safety,on_delete=models.CASCADE,null=True,blank=True)
    print_hazard=models.CharField(max_length=200)
    mit_date=models.DateField(null=True,blank=True)
    auditable_work=models.CharField(max_length=200)
    comp_date=models.DateField(null=True,blank=True)
    remarks=models.CharField(max_length=200)
    class Meta:
       db_table="safetytable"     

safety/forms.py
from django import forms
from employee.models import MineDetails
from safety.models import Safety,SafetyTable
class SafetyForm(forms.ModelForm):
    mine=forms.ModelChoiceField(label='Name of the Mine',queryset=MineDetails.objects.all(),widget=forms.Select(attrs={'class':'form-control'}))
    owner=forms.CharField(label='Name of the Owner',max_length=200)
    agent=forms.CharField(label='Name of the Agent',max_length=200)
    manager=forms.CharField(label='Name of the Manager',max_length=200)
    status_report=forms.DateField()
    class Meta:
        model=Safety
        fields = '__all__'

class SafetyTableForm(forms.ModelForm):
    print_hazard=forms.CharField(label='hazard',max_length=500)
    mit_date=forms.DateField()
    auditable_work=forms.CharField(max_length=1000)
    comp_date=forms.DateField()
    remarks=forms.CharField(max_length=200)
    class Meta:
        model=SafetyTable
        fields = '__all__'

   

safety/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from safety.forms import SafetyForm, SafetyTableForm
from safety.models import Safety, SafetyTable
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse


def safe(request):
    form1 = SafetyForm()
    form2 = []
    form2.append(SafetyTableForm())
    if request.method == "POST":
        print_hazard = request.POST.getlist('print_hazard')
        mit_date = request.POST.getlist('mit_date')
        auditable_work = request.POST.getlist('auditable_work')
        comp_date = request.POST.getlist('comp_date')
        remarks = request.POST.getlist('remarks')
        form = SafetyForm(request.POST or None)
        if form.is_valid():
            safety_id = form.save()
            safety_table = []
            for i in range(0, len(print_hazard)):
                safety_table.append(SafetyTable(safety_id=safety_id,
                                                print_hazard=print_hazard[i],
                                                mit_date=mit_date[i],
                                                auditable_work=auditable_work[i],
                                                comp_date=comp_date[i],
                                                remarks=remarks[i]))

            SafetyTable.objects.bulk_create(safety_table)

            return redirect('safety:show',str(safety_id.id))

    return render(request, 'safety/index.html', {'form1': form1, 'form2': form2})


def show(request,pk,template_name='safety/show.html'):
    safetytable=[]
    safety = Safety.objects.get(pk=pk)
    safetytable.append(SafetyTable.objects.filter(safety_id=safety))

    return render(request, template_name,{'safetytable': safetytable,'safety':safety})


def manage(request):
    safety = Safety.objects.all()
    return render(request, 'safety/manage.html', {'safety': safety})


def edit(request, pk, template_name='safety/index.html'):
    safety_instance = Safety.objects.get(pk=pk)
    form1 = SafetyForm(request.POST or None, instance=safety_instance)
    form2=[]
    safety_table=SafetyTable.objects.filter(safety_id=safety_instance.pk)
    present_ids=[]
    current_ids=[]
    for safety in safety_table:
        present_ids.append(safety.pk)
        form2.append(SafetyTableForm(instance=safety))

    if request.method=="POST":
        print('present_ids',present_ids)
        try:
            form2=[]
            print_hazard = request.POST.getlist('print_hazard')
            mit_date = request.POST.getlist('mit_date')
            auditable_work = request.POST.getlist('auditable_work')
            comp_date = request.POST.getlist('comp_date')
            remarks = request.POST.getlist('remarks')
            safety_ids=request.POST.getlist('safetytable_id')
            print('safety_ids',safety_ids)
            if form1.is_valid():
                form1.save()
            i=0
            for id in safety_ids: # 1 2 3 1 2
                current_ids.append(int(id))

                instance = SafetyTable.objects.get(pk=id)
                instance.print_hazard=print_hazard[i]
                instance.mit_date=mit_date[i]
                instance.auditable_work=auditable_work[i]
                instance.comp_date=comp_date[i]
                instance.remarks=remarks[i]
                instance.save()
                print('instance',instance.remarks)
                form2.append(SafetyTableForm(instance=instance))
                i+=1
            cc=list(set(present_ids).difference(current_ids))

            for c in cc:
                instance = SafetyTable.objects.get(pk=c)
                instance.delete()

            for j in range(i, len(print_hazard)):
                safety_table=SafetyTable(safety_id=safety_instance,
                                                print_hazard=print_hazard[j],
                                                mit_date=mit_date[j],
                                                auditable_work=auditable_work[j],
                                                comp_date=comp_date[j],
                                                remarks=remarks[j])
                safety_table.save()
                form2.append(SafetyTableForm(instance=safety_table))
            messages.success(request,"Successfully Updated")
            return redirect('safety:manage')
        except Exception as e:

            messages.error(request,"Something Went Wrong "+str(e))
            pass
    return render(request, template_name, {'form1': form1,'form2':form2})


def delete(request, pk):
    try:
        safety=Safety.objects.get(pk=pk)
        safety.delete()
        messages.success(request,"Deleted Successfully")
    except :
        messages.error(request,"Something went wrong")
    return redirect('safety:manage')


def fetch_dropdownlist(request):
    data = {}
    owner = []
    agent = []
    manager = []

    if request.is_ajax():
        id = request.GET.get('id', None)
        safety = Safety.objects.filter(mine_id=id)
        ow = safety.values('owner').distinct()
        ag = safety.values('agent').distinct()
        man = safety.values('manager').distinct()
        for o in ow:
            owner.append({'name': o['owner']})
        for a in ag:
            agent.append({'name': a['agent']})
        for m in man:
            manager.append({'name': m['manager']})

        # for s in safety:
        #     owner.append({'name':s.owner.distinct()})
        #     agent.append({'name': s.agent})
        #     manager.append({'name': s.manager})
        data['result'] = {
            'owner': owner,
            'agent': agent,
            'manager': manager
        }
    else:
        data['error'] = "Not Ajax"

    return JsonResponse(data)

safety/templates/safety/index.html
{% extends "base.html" %}
{% block content %}
    {% load static %}
    <div class="container">
        <div class="row">
            <section class="col-md-12">
                <div class="row text-center">
                    <h3 class="page-header"><b>STATUS REPORT ON PROGRESS MADE INTO MITIGATION OF ALL THE IDENTIFIED
                        PRINCIPAL HAZARDS</b>
                        <small>Here you can add/edit status report</small>
                    </h3>
                </div>
                <!-- Table content -->
                <div class="row">
                    <div class="form-group">
                        <form class="form-horizontal" method="post" enctype="multipart/form-data">{% csrf_token %}
                            <fieldset class="scheduler-border">
                                <legend class="scheduler-border">
                                    <span style="color: blue; "> Mine Details</span>
                                </legend>
                                <div class="row">

                                    <div class="col-md-6">
                                        <div class="col-md-4">
                                            <label for="id_empid" class="" id="emp">Name of the Mine :<span
                                                    style="color: red; ">*
                                            </span>
                                            </label>
                                        </div>
                                        <div class="col-md-8">
                                            {{ form1.mine }}
                                            <span style="color:red">{{ form1.Mine.errors|striptags }}</span>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="col-md-4">
                                            <label for="id_own" class="" id="own">Name of the Owner: <span
                                                    style="color: red; ">*
                                            </span></label>
                                        </div>
                                        <div class="col-md-8">
                                            {{ form1.owner }}
                                            <span style="color:red">{{ form1.owner.errors|striptags }}</span>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="col-md-4">
                                            <label for="id_agent" class="" id="agent1"> Name of the Agent: <span
                                                    style="color: red; ">
                                                *</span></label>
                                        </div>
                                        <div class="col-md-8">
                                            {{ form1.agent }}
                                            <span style="color:red">{{ form1.agent.errors|striptags }}</span>

                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="col-md-4">
                                            <label for="id_own" class="" id="manag">Name of the Manager:<span
                                                    style="color: red; ">*
                                            </span></label>
                                        </div>
                                        <div class="col-md-8">
                                            {{ form1.manager }}
                                            <span style="color:red">{{ form1.manager.errors|striptags }}</span>
                                        </div>
                                    </div>
                                </div>
                                <br>
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="col-md-4">
                                            <label for="id_status" class="" id=""> Status report for the quarter ending
                                                on:
                                                <span style="color: red; ">*</span></label>
                                        </div>
                                        <div class="col-md-8">
                                            <div class='input-group date' id='doo_date_time_picker'>
                                                {{ form1.status_report }}

                                                <span class="input-group-addon">
                                                <span class="glyphicon glyphicon-calendar"></span>
                                            </span>
                                            </div>
                                        </div>
                                        <span style="color:red">{{ form1.status_report.errors|striptags }}</span>
                                    </div>
                                </div>
                                <br>

                                <div class=table-table-resposive>
                                    <table class="table table-striped table-bordered" id="test">
                                        <thead>
                                        <th>List of Principal Hazard
                                            Identified.
                                        </th>

                                        <th>Mitigation Date as per
                                            formulated SMP.
                                        </th>

                                        <th>Details of auditable
                                            work plans made for mitigation.
                                        </th>

                                        <th>Actual date of completion
                                            as per workplan.
                                        </th>
                                        <th>Remarks, if any</th>
                                        <th></th>
                                        </thead>
                                        <tbody>
                                        {% for f in form2 %}
                                            <tr>
                                                <input type="hidden" name="safetytable_id" value="{{ f.instance.id }}"/>
                                                <td>{{ f.print_hazard }}
                                                    <span style="color:red">{{ form2.print_hazard.errors|striptags }}</span>
                                                </td>
                                                <td>
                                                    <div class='input-group date' id='doo2_date_time_picker'>
                                                        {{ f.mit_date }}
                                                        <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>
                                                    </div>
                                                </td>

                                                <td>{{ f.auditable_work }}
                                                    <span style="color:red">{{ form2.auditable_work.errors|striptags }}</span>
                                                </td>
                                                <td>
                                                    <div class='input-group date' id='doo_date_time_picker'>
                                                        {{ f.comp_date }}
                                                        <span class="input-group-addon">
                                                        <span class="glyphicon glyphicon-calendar"></span>
                                                    </span>
                                                    </div>
                                                </td>
                                                <td>{{ f.remarks }}</td>
                                                <td><a href="#"><span id="delete-row"
                                                                      class="glyphicon glyphicon-trash delete-row"></span></a>
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                        <br>

                                    </table>
                                </div>
                                <button id="btnAdd" type="button" class="btn btn-primary add_field_button"
                                        data-toggle="tooltip" data-original-title="Add more controls">Add <i
                                        class="glyphicon glyphicon-plus-sign"></i>&nbsp;
                                </button>
                                <br>
                                <br>
                                <div class="text-center">
                                    <input type="submit" class="btn btn-primary" value="Submit"/>
                                </div>
                            </fieldset>
                        </form>
                    </div>
                </div>
                <!--end Table content -->
            </section>
        </div>
    </div>
    <style>
        fieldset.scheduler-border {
            border: solid 1px #DDD !important;
            padding: 0 10px 10px 10px;
            border-bottom: none;
        }

        legend.scheduler-border {
            width: auto !important;
            border: none;
            font-size: 14px;
        }

        fieldset ul {
            list-style: none
        }

        .red-tooltip + .tooltip > .tooltip-inner {
            background-color: #fff;
        }

        .red-tooltip + .tooltip > .tooltip-arrow {
            border-bottom-color: #fff;
        }
    </style>
    <script>
        $(document).ready(function () {
            $(function () {

                var date_from = $('.date').datetimepicker({
                    format: 'YYYY-MM-DD'
                });
                date_from.children()[0].id = "id_date_fr";
                date_from.children()[0].required = "true";
            });
            var max_fields = 100;
            var wrapper = $("#fields");
            $('button#btnAdd').click(function (e) {
                e.preventDefault();
                $('#test').append(
                    '<tr>' +
                    '<td><input type="text" name="print_hazard"  maxlength="500" required="" id="id_print_hazard"></td>' +
                    '<td><div class="input-group date" id="doo2_date_time_picker">' +
                    '<input type="text" name="mit_date" required="" id="id_mit_date"><span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>' +
                    '</div></td>' +
                    '<td><input type="text" name="auditable_work" maxlength="1000" required="" id="id_auditable_work"></td>' +
                    '<td><div class="input-group date" id="doo_date_time_picker">' +
                    '<input type="text" name="comp_date" required="" id="id_comp_date">' +
                    ' <span class="input-group-addon">' +
                    '<span class="glyphicon glyphicon-calendar">' + '</span>' +
                    '</span></div></td>' +
                    '<td><input type="text" name="remarks" maxlength="200" required="" id="id_remarks"></td>' +
                    '<td><a href="#"><span id="delete-row" class="glyphicon glyphicon-trash delete-row"></span></a></td></tr>');
                var date_from = $('.date').datetimepicker({
                    format: 'YYYY-MM-DD'
                });

            });
            $("body").delegate("span.delete-row", "click", function () {
                let row = $(this).parent().parent().parent();
                if (confirm("R u sure you want to delete this row")) {
                    row.remove();
                }
            });
        });
        var x;
    </script>
{% endblock %}

safety/templates/safety/manage.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="row">
            <section class="col-md-12">
                <h3 class="page-header text-center"><b>MANAGE SAFETY</b></h3>
                <div class="row">

                </div>
                <div class="table-responsive">
                    <table class="table table-bordered" id=safety>
                        <thead>
                        <tr>
                            <th>Sl.No</th>
                            <th>Name of the Mine</th>
                            <th>Name of the Owner</th>
                            <th>Name of the Agent</th>
                            <th>Name of the Manager</th>
                            <th>Status report for the quarter ending On</th>
                            <th>View</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for s in safety %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ s.mine }}</td>
                                <td>{{ s.owner }}</td>
                                <td>{{ s.agent }}</td>
                                <td>{{ s.manager }}</td>
                                <td>{{ s.status_report }}</td>
                                <td><a class="btn btn-info" href="{% url 'safety:show' s.id %}"> View <span
                                        class="glyphicon glyphicon-list"></span></a></td>
                                <td><a class="btn btn-warning"href="{% url 'safety:edit' s.id %}"> Edit <span
                                        class="glyphicon glyphicon-pencil"></span></a></td>
                                <td>
                                    <div class="btn btn-danger delete" data-url="{% url 'safety:delete' s.id %}">
                                        Delete
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
        </div>
    </div>
    <script>
    $(document.body).on("click", ".delete", function () {

        $("#sureDelete").attr("href", $(this).data('url'));
        $('#update_info').modal('show');

    });
    </script>
{% endblock %}