SMS/urls.py
from django.urls import path

from SMS import views

app_name = 'sms'
urlpatterns = [
    path('', views.index, name='index'),
    # path('update_news/<int:pk>',views.update_news,name='update_news'),
    # path('get_news_ajax/',views.get_news_ajax,name='get_news_ajax'),
    # path('update_news_download_number_ajax/',views.update_news_download_number_ajax,name='update_news_download_number_ajax'),
    # path('delete_news_ajax/',views.delete_news_ajax,name='delete_news_ajax'),
]

apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django.urls import include, path
from django.contrib import admin


from theme import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home),
    path('base_layout',views.base_layout,name='base_layout'),

    path('employee/',include('employee.urls',namespace='employee')),
    path('MinersTracking/',include('MinersTracking.urls',namespace='MinersTracking')),
    path('FireExp/',include('FireExp.urls',namespace='FireExp')),
    path('Controlling/',include('Controlling.urls',namespace='Controlling')),
    path('DGMS_Forms/',include('DGMS_Forms.urls',namespace='DGMS_Forms')),
    path('Strata/',include('Strata.urls',namespace='Strata')),
    path('theme/',include('theme.urls',namespace='theme')),


    path('accounts/', include('accounts.urls')),
    path('snippets/', include('snippets.urls')),
    path('gasmonitoring/', include('gasmonitoring.urls', namespace='gasmonitoring')),
    path('temp_monitoring/', include('temp_monitoring.urls', namespace='temp_monitoring')),
    path('gasmonitoring_wifi/', include('gasmonitoring_wifi.urls', namespace='gasmonitoring_wifi')),
    path('inventory_management/', include('inventory_management.urls', namespace='inventory_management')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('Training_Rescue_Accident/', include('Training_Rescue_Accident.urls', namespace='Training_Rescue_Accident')),
    path('ProductionMonitoring/', include('ProductionMonitoring.urls',namespace='ProductionMonitoring')),
    path('sensor/', include('sensor.urls', namespace='sensor')),### prasanjit dey(gas monitoring)
    path('water_level_monitoring/', include('water_level_monitoring.urls', namespace='water_level_monitoring')),### SS MISHRA(water monitoring)
    # path('tags_input/', include('tags_input.urls', namespace='tags_input')),
    path('sms/', include('SMS.urls', namespace='sms')),
    path('news/', include('news.urls', namespace='news')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('wm_test/', include('wm_test.urls', namespace='weather_monitoring')),
    path('setting/', include('setting.urls', namespace='setting')),
    path('Slope/', include('Slope.urls', namespace='Slope')),
    path('safety/', include('safety.urls', namespace='safety')),
    # path('',include('pwa.urls')),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'apps.views.error_404_view'

inventory_management/urls.py
from django.urls import path
from inventory_management import views


app_name = 'inventory_management'

urlpatterns = [
      # ----------------------Supplier Details---------------------------------
    path('supplier_add/', views.supplier_add, name='supplier_add'),
    path('supplier_manage/', views.supplier_manage, name='supplier_manage'),
    path('supplier_edit/<int:pk>', views.supplier_edit, name='supplier_edit'),
    path('supplier_delete/<int:pk>', views.supplier_delete, name='supplier_delete'),
       # ----------------------Category Details---------------------------------
    path('category_add', views.category_add, name='category_add'),
    path('category_manage/', views.category_manage, name='category_manage'),
    path('category_edit/<int:pk>', views.category_edit, name='category_edit'),
    path('category_delete/<int:pk>', views.category_delete, name='category_delete'),

      # ----------------------Product Details---------------------------------
    path('product_add/', views.product_add, name='product_add'),
    path('product_manage/', views.product_manage, name='product_manage'),
    path('product_edit/<int:pk>', views.product_edit, name='product_edit'),
    path('product_delete/<int:pk>', views.product_delete, name='product_delete'),


      # ----------------------Ajax---------------------------------
    path('fetch_supplier_ajax/', views.fetch_supplier_ajax, name='fetch_supplier_ajax'),

          # ----------------------View All---------------------------------
    path('view_product/', views.view_product, name='view_product'),

  
  #----------------------Reports----------------------------------------------
    path('view_expiredReport/', views.view_expiredReport, name='view_expiredReport'),
    path('fetch_category_ajax/', views.fetch_category_ajax, name='fetch_category_ajax'),
    
    path('fetch_product_ajax/', views.fetch_product_ajax, name='fetch_product_ajax'),
    path('fetch_expiry_report_ajax/', views.fetch_expiry_report_ajax, name='fetch_expiry_report_ajax'),
    
    path('CategoryWiseReport/', views.CategoryWiseReport, name='CategoryWiseReport'),
    path('fetch_CategoryWiseReport_ajax/', views.fetch_CategoryWiseReport_ajax, name='fetch_CategoryWiseReport_ajax'),
    path('CategoryWiseViewAll/', views.CategoryWiseViewAll, name='CategoryWiseViewAll'),
    path('BatchWiseViewAll/', views.BatchWiseViewAll, name='BatchWiseViewAll'),

    #----------------------Reports----------------------------------------------
    path('utilizationReport/', views.utilizationReport, name='utilizationReport'),
    path('fetch_longpending/', views.fetch_longpending, name='fetch_longpending'),

     #----------------------Outof stock Reports----------------------------------------------
    path('OutOfStock/', views.OutOfStock, name='OutOfStock'),
    path('ExpiredProdView/', views.ExpiredProdView, name='ExpiredProdView'),

     

     #----------------------Deduct Inventory/ Lost Goods and Stock Adjustment----------------------------------------------
      
    path('Inventory_deduct', views.Inventory_deduct, name='Inventory_deduct'),
    path('fetch_inventory_deduct_ajax', views.fetch_inventory_deduct_ajax, name='fetch_inventory_deduct_ajax'),
    path('update_inventory_ajax', views.update_inventory_ajax, name='update_inventory_ajax'),


    #----------------------Deduct branch Inventory/ Lost Goods and Stock Adjustment----------------------------------------------
    path('inventory_branchdeduct', views.inventory_branchdeduct, name='inventory_branchdeduct'),
    path('fetch_branch_category', views.fetch_branch_category, name='fetch_branch_category'),
    path('fetch_deduct_branch_inventory', views.fetch_deduct_branch_inventory, name='fetch_deduct_branch_inventory'),
    # path('update_inventory_ajax', views.update_inventory_ajax, name='update_inventory_ajax'),
    path('update_branch_inventory_ajax', views.update_branch_inventory_ajax, name='update_branch_inventory_ajax'),
    
  

    path('search', views.search, name='search'),
    # # url(r'^ajax_calls/search/', autocompleteModel),
    path('fetch_search_ajax', views.fetch_search_ajax, name='fetch_search_ajax'),

    path('inventory_reorder', views.inventory_reorder, name='inventory_reorder'),
    path('fetch_inventory_reorder_ajax', views.fetch_inventory_reorder_ajax, name='fetch_inventory_reorder_ajax'),
    path('update_inventory_ajax_add', views.update_inventory_ajax_add, name='update_inventory_ajax_add'),
    path('fetch_batch_ajax/', views.fetch_batch_ajax, name='fetch_batch_ajax'),
    
     # ----------------------Branch Details---------------------------------

    path('distribute_prod/', views.distribute_prod, name='distribute_prod'),
    path('fetch_mine_branch', views.fetch_mine_branch, name='fetch_mine_branch'),
    path('fetch_assign_id', views.fetch_assign_id, name='fetch_assign_id'),
    path('distribution', views.distribution, name='distribution'),
    
 
     # ----------------------Branch Details---------------------------------
    path('settings', views.settings, name='settings'),
    path('manageAll', views.manageAll, name='manageAll'),
    path('branch_manage/', views.branch_manage, name='branch_manage'),
    path('branch_edit/<int:pk>', views.branch_edit, name='branch_edit'),
    path('branch_delete/<int:pk>', views.branch_delete, name='branch_delete'),
    path('outlet_viewall/', views.outlet_viewall, name='outlet_viewall'),
    path('OutletOutOfStock/', views.OutletOutOfStock, name='OutletOutOfStock'),
    path('OutletExpiredView/', views.OutletExpiredView, name='OutletExpiredView'),

     # ----------------------Delete Expired---------------------------------
    path('deleteExpired/', views.deleteExpired, name='deleteExpired'),
    
    # ----------------------About to  Expired---------------------------------
    path('abtExpired/', views.abtExpired, name='abtExpired'),
    path('fetch_abtExpire/', views.fetch_abtExpire, name='fetch_abtExpire'),
    # ----------------------About to  Out Of Stock---------------------------------

    path('abtOutOfStock/', views.abtOutOfStock, name='abtOutOfStock'),
    path('fetch_abtOutOfStock/', views.fetch_abtOutOfStock, name='fetch_abtOutOfStock'),

    #-----------------------Alternate Product-------------------------------------
    path('altProd_manage/', views.altProd_manage, name='altProd_manage'),
    path('altProd_edit/<int:pk>', views.altProd_edit, name='altProd_edit'),
    path('altProd_delete/<int:pk>', views.altProd_delete, name='altProd_delete'),

 
    

]

setting/urls.py
from django.urls import path
from setting import views


app_name='setting'

urlpatterns = [
    path('manage_constant', views.manage_constant,name='manage_constant'),
    path('add_constant', views.add_constant, name='add_constant'),
    path('edit_constant/<int:id>', views.edit_constant,name='edit_constant'),
    path('delete_constant/<int:id>', views.delete_constant,name='delete_constant'),
    path('globalWarningFunction', views.globalWarningFunction,name='globalWarningFunction'),
    path('change_language/<str:lang>',views.change_language,name="change_language"),
    path('check',views.checkNotification,name='checkNotification'),
]

inventory_management/models.py
# Create your models here.
from django.db import models
from django.utils import timezone
# Create your models here.
# Create your models here.
from django.db import models
# Create your models here.
from employee.models import MineDetails
from datetime import date, datetime
# from django.db import models
# from phone_field import PhoneField
# from phonenumber_field.modelfields import PhoneNumberField


class SupplierModel(models.Model):
    mine_id = models.ForeignKey(MineDetails, on_delete=models.CASCADE, null=True, blank=True)
    # business_name = models.CharField(max_length=100, null=True, blank=True)
    business_name = models.CharField(max_length=100,null=True,blank=True)
    business_website = models.CharField(max_length=100, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    # mobile_no=models.CharField(max_length=100,default='0000000000',blank=True,null=True)
    mobile_no = models.BigIntegerField(blank=True,null=True)
    # mobile_no=PhoneNumberField(null=False, blank=False, unique=True)
    email= models.EmailField(null=True,blank=True,default='abc@gmail.com')
    pincode= models.IntegerField(blank=True, null=True)
    address= models.CharField(max_length=400, null=True, blank=True)
    landmark= models.CharField(max_length=400, null=True, blank=True)
    area= models.CharField(max_length=200, null=True, blank=True)
    city= models.TextField(default='')
    state= models.CharField(max_length=100,blank=True)
    map_loc= models.CharField(max_length=400, null=True, blank=True)
    pan= models.CharField(max_length=200, null=True, blank=True)
    gstin= models.CharField(max_length=200, null=True, blank=True)
    notes= models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
     return self.business_name
    class Meta:
        db_table = "Supplier_Details"

class CategoryModel(models.Model):
    prod_category = models.CharField(max_length=100,null=True)
    
    def __str__(self):
        return self.prod_category
    class Meta:
        db_table = "category_details"


class AlternateProdModel(models.Model):
    prod_id = models.CharField(max_length=100,null=True)
    mine_id = models.IntegerField(null=True, blank=True)
    batch_number= models.CharField(max_length=100,null=True)
    alter_product = models.CharField(max_length=100,null=True)
    
    def __str__(self):
        return self.prod_id
    class Meta:
        db_table = "AlternateProdModel"
        

class BranchModel(models.Model):
    mine_id = models.ForeignKey(MineDetails, on_delete=models.CASCADE, null=True, blank=True)
    branch_nm = models.CharField(max_length=100,null=True)  
    def __str__(self):
        return self.branch_nm
    class Meta:
        db_table = "branch_details"
        
class ProductModel(models.Model):
    mine_id = models.ForeignKey(MineDetails, on_delete=models.CASCADE, null=True, blank=True)
    business_name = models.IntegerField(null=True, blank=True)
    #########   Product Details  #################
    prod_category = models.ForeignKey(CategoryModel, on_delete=models.CASCADE, null=True, blank=True)
    prod_name = models.CharField(max_length=100,null=True)
    # #########   Purchase As  #################
    alternate_prod = models.CharField(max_length=100,null=True)
    unit = models.CharField(max_length=100,null=True)

        # #########   PRICING AND INVENTORY  #################
    invoice_no = models.CharField(max_length=100, null=True, blank=True)
    prod_expiry=models.DateField(blank=True,null=True,default=date.today)
    quantity= models.IntegerField(null=True)
    price= models.FloatField(null=True, blank=True)
    batch_number = models.CharField(max_length=100,null=True)
    barcode = models.CharField(max_length=100,null=True)
    tax= models.CharField(max_length=100,null=True, blank=True)
    rate=models.FloatField(null=True,blank=True,default='18.0')
    total_tax= models.FloatField(null=True)
    net_amount= models.FloatField(null=True)

        # #########   Additional  Details   #################
    info_any=models.CharField(max_length=200,null=True)
    entry_date=models.DateField(blank=True,null=True,default=date.today)
    initial_quantity=models.IntegerField(blank=True,null=True)
    
    def __str__(self):
        return self.prod_name
    def __str__(self):
        return self.batch_number
 
    class Meta:
        db_table = "product_details"

class DistributeModel(models.Model):
    # token=models.CharField(max_length=100,null=True)
    distribution_date=models.DateField(blank=True,null=True,default=date.today)
    # distribution_date = models.DateTimeField(default=datetime.now, blank=True)
    mine_id=models.IntegerField(null=True)
    mine_name = models.CharField(max_length=100,null=True)
    branch_name = models.CharField(max_length=100,null=True)
    prod_category = models.CharField(max_length=100,null=True)
    prod_name = models.CharField(max_length=100,null=True)
    batch_number = models.CharField(max_length=100,null=True)
    # unit = models.CharField(max_length=100,null=True)
    # net_weight = models.CharField(max_length=100,null=True)
    assign_quantity=models.IntegerField(null=True)
    quantity= models.CharField(max_length=100,null=True) 
    prod_unique_id=models.IntegerField(null=True)

    class Meta:
        db_table = "Distribution_details"

class DeductModel(models.Model):
    # deduct_date= models.DateTimeField(default=timezone.now)
    deduct_date=models.DateField(blank=True,null=True,default=date.today)
    created_on=models.DateTimeField(null=True)
    productDetails_id = models.IntegerField(null=True)
    mine_id = models.CharField(max_length=100,null=True)
    branch_id = models.CharField(max_length=100,null=True)
    prod_category = models.CharField(max_length=100,null=True)
    prod_name = models.CharField(max_length=100,null=True)
    barcode = models.CharField(max_length=100,null=True)
    batch_number = models.CharField(max_length=100,null=True) 
    quantity= models.IntegerField(null=True)
    outstock= models.IntegerField(null=True)
    updated_quantity= models.IntegerField(null=True)

    class Meta:
        db_table = "deduct_details"

class ReorderModel(models.Model):
    Reorder_date= models.DateTimeField(default=timezone.now)
    creationdate=models.DateTimeField(default=timezone.now)
    mine_id = models.CharField(max_length=100,null=True)
    prod_category = models.CharField(max_length=100,null=True)
    product_id = models.IntegerField(null=True)
    prod_name = models.CharField(max_length=100,null=True)
    barcode = models.CharField(max_length=100,null=True)
    batch_number = models.CharField(max_length=100,null=True) 
    quantity= models.IntegerField(null=True)
    addedstock= models.IntegerField(null=True)
    updated_quantity= models.IntegerField(null=True)

    class Meta:
        db_table = "reorder_details"

inventory_management/templates/SupplierDetails.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}
<!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
<!--<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">-->
<!--<link rel="stylesheet" href="{% static '/css/w3.css' %}">-->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<div class="container">
    <div class="row">
        <section class="col-md-12">
           <h1 class="page-header"> <centre>&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp &nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Add Supplier Details
                <small>&nbsp&nbsp&nbspHere you can add/edit basic info of Item supplier</small>
                </h1>  </centre>
    

            <div class="row">
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}

            <div class="alert alert-success">{{ message }}</div>
            {% endfor %}
        </ul>
    {% endif %}
</div>
 <div class="row">
{% if form.errors %}
<div class="alert alert-success">
  <ul>

    {% for key,value in form.errors.items %} 
      <li>{{ key|escape }} : {{ value|escape }}</li>
    {% endfor %}
  </ul>
{% endif %} 
</div>
    </div>


            <div class="row text-center">
                <div class="col-md-12">
                    <a class="btn btn-primary" href="{% url 'inventory_management:supplier_manage' %}">Manage Supplier</a>
                     <a class="btn btn-primary" href="{% url 'inventory_management:supplier_add' %}">Add Supplier</a>
                </div>
            </div>
            <hr>
            <!-- Table content -->
            <div class="row">
                <div class="form-group">
                    <form class="form-horizontal" method="post" enctype="multipart/form-data" >{% csrf_token %}
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border"><font color="blue">Clinic Specific Details</font></legend>
                        <div class="form-group col-md-12">
                            <div class="col-md-12">
                                <div class="col-md-4">
                                    <label name="mine_id" for="" class="" id="mine_id">Choose Clinic Area:<font color="red">*</font></label>
                                </div>
                                <div class="col-md-8">
                                    {{form.mine_id}}
                            <!--      <input type="hidden" id="mine_idd" type="text" class="form-control" value="{{ form.mine_id }}" > -->
                                  
                                </div>
                            </div>
                        </div>
                        </fieldset>
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border"><font color="blue">Business Details</font></legend>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_business_name" name="id_business_name" class="" id="id_business_name">Business Name<font color="red">*</font></label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.business_name}}
                                <!--  <input list="businesslist" name="business"  class="form-control"  placeholder="Start typing business name........."  >

                                    <datalist id="businesslist" >
                            
                                        {% for business in DatalistQS %}
                                    <option value="{{ business.business_name}}">{{business.business_name}}</option>
                                        {% endfor %}
                               
                                   
                                    </datalist> -->



                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_business_website" name="id_business_website" class="" id="id_business_website">Business Website</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.business_website}}
                                    </div>
                                </div>
                            </div>
                    </fieldset>

                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border"><font color="blue">Contact Person</font></legend>
                             <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_name" name="id_name" class="" id="id_name">Name<font color="red">*</font></label>
                                    </div>
                                    <div class="col-md-8">
                                       {{form.name}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="mobile_no" name="mobile_no" class="" id="mobile_no">Mobile Number<font color="red">*</font></label>
                                    </div>
                                    <div class="col-md-8">
                                         {{form.mobile_no}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_email" name="id_email" class="" id="id_email">Email</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.email}}
                                    </div>
                                </div>
                            </div>
                        </fieldset>
                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border"><font color="blue">Billing Address</font></legend>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="pin" name="pin" class="" id="pin">Pincode</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.pincode}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="address" name="address" class="" id="address">Address</label>
                                    </div>
                                    <div class="col-md-8">
                                         {{form.address}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="landmark" name="landmark" class="" id="landmark">Landmark</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.landmark}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_area" name="id_area" class="" id="id_area">Area</label>
                                    </div>
                                    <div class="col-md-8">
                                         {{form.area}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_city" name="id_city" class="" id="id_city">City</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.city}}
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_state" name="id_state" class="" id="id_state">State<font color="red">*</font></label>
                                    </div>
                                    <div class="col-md-8">
                                         {{form.state}}
                                    </div>
                                </div>
                             <br/><br/> <br/><br/>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_map_location" name="id_map_location" class="" id="id_map_location">Map Location</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.map_loc}}
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <fieldset class="scheduler-border">
                            <legend class="scheduler-border"><font color="blue">Tax Details</font></legend>
                             <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_pan" name="id_pan" class="" id="id_pan">PAN /TIN</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.pan}}
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_gstin" name="id_gstin" class="" id="id_gstin">GSTIN</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.gstin}}
                                    </div>
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-6">
                                    <div class="col-md-4">
                                        <label for="id_notes" name="id_notes" class="" id="id_notes">Notes</label>
                                    </div>
                                    <div class="col-md-8">
                                        {{form.notes}}
                                    </div>
                                </div>
                            </div>
                        </fieldset>

                        <div class="text-center">
                            <input type="submit" class="btn btn-primary" value="Submit"/>
                        </div>
                    </form>
                </div>
            </div><!--end Table content -->
        </section>
    </div>
</div>

<style>

    fieldset.scheduler-border {
    border: solid 1px #DDD !important;
    padding: 0 10px 10px 10px;
    border-bottom: none;
}

legend.scheduler-border {
    width: auto !important;
    border: none;
    font-size: 14px;
}
fieldset ul {list-style:none}

</style>
<script>

$(document).ready(function(){
        $("#id_mine_id").addClass('form-control');

});
$(function() {
    $( ".datepicker" ).datepicker({
      changeMonth: true,
      changeYear: true,
      yearRange: "1900:2012",
      // You can put more options here.

    });
  });


</script>

{% endblock %}