SMS/urls.py
from django.urls import path

from SMS import views

app_name = 'sms'
urlpatterns = [
    path('', views.index, name='index'),
    # path('update_news/<int:pk>',views.update_news,name='update_news'),
    # path('get_news_ajax/',views.get_news_ajax,name='get_news_ajax'),
    # path('update_news_download_number_ajax/',views.update_news_download_number_ajax,name='update_news_download_number_ajax'),
    # path('delete_news_ajax/',views.delete_news_ajax,name='delete_news_ajax'),
]

apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django.urls import include, path
from django.contrib import admin


from theme import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home),
    path('base_layout',views.base_layout,name='base_layout'),

    path('employee/',include('employee.urls',namespace='employee')),
    path('MinersTracking/',include('MinersTracking.urls',namespace='MinersTracking')),
    path('FireExp/',include('FireExp.urls',namespace='FireExp')),
    path('Controlling/',include('Controlling.urls',namespace='Controlling')),
    path('DGMS_Forms/',include('DGMS_Forms.urls',namespace='DGMS_Forms')),
    path('Strata/',include('Strata.urls',namespace='Strata')),
    path('theme/',include('theme.urls',namespace='theme')),


    path('accounts/', include('accounts.urls')),
    path('snippets/', include('snippets.urls')),
    path('gasmonitoring/', include('gasmonitoring.urls', namespace='gasmonitoring')),
    path('temp_monitoring/', include('temp_monitoring.urls', namespace='temp_monitoring')),
    path('gasmonitoring_wifi/', include('gasmonitoring_wifi.urls', namespace='gasmonitoring_wifi')),
    path('inventory_management/', include('inventory_management.urls', namespace='inventory_management')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('Training_Rescue_Accident/', include('Training_Rescue_Accident.urls', namespace='Training_Rescue_Accident')),
    path('ProductionMonitoring/', include('ProductionMonitoring.urls',namespace='ProductionMonitoring')),
    path('sensor/', include('sensor.urls', namespace='sensor')),### prasanjit dey(gas monitoring)
    path('water_level_monitoring/', include('water_level_monitoring.urls', namespace='water_level_monitoring')),### SS MISHRA(water monitoring)
    # path('tags_input/', include('tags_input.urls', namespace='tags_input')),
    path('sms/', include('SMS.urls', namespace='sms')),
    path('news/', include('news.urls', namespace='news')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('wm_test/', include('wm_test.urls', namespace='weather_monitoring')),
    path('setting/', include('setting.urls', namespace='setting')),
    path('Slope/', include('Slope.urls', namespace='Slope')),
    path('safety/', include('safety.urls', namespace='safety')),
    # path('',include('pwa.urls')),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'apps.views.error_404_view'

sensor/urls.py
from django.urls import path

# from sensor import views
from . import views

# from arduino import views
app_name = 'sensor'

urlpatterns = [
    path('node_manage/', views.node_manage, name='node_manage'),
    path('node_add', views.node_add, name='node_add'),
    path('node_edit/<str:pk>', views.node_edit, name='node_edit'),
    path('node_delete/', views.node_delete, name='node_delete'),
    path('ellicots/<str:pk>', views.ellicots, name='ellicots'),
    path('line_chart_ratio_graph/<str:pk>', views.line_chart_ratio_graph, name='line_chart_ratio_graph'),
    path('line_chart_ratio_graph_ajax', views.line_chart_ratio_graph_ajax, name='line_chart_ratio_graph_ajax'),

    path('youngs_ratio_graph/<str:pk>', views.youngs_ratio_graph, name='youngs_ratio_graph'),
    path('youngs_ratio_graph_ajax', views.youngs_ratio_graph_ajax, name='youngs_ratio_graph_ajax'),
    path('ellicots_ajax', views.ellicots_ajax, name='ellicots_ajax'),

    path('locate_node/<str:mine_id>/<str:node_id>', views.locate_node, name='locate_node'),

    path('fetch_node_ajax', views.fetch_node_ajax, name='fetch_node_ajax'),

    path('manage_sensor/<str:mine_id>/<str:node_id>', views.manage_sensor, name='manage_sensor'),

    path('add_sensor/<str:mine_id>/<str:node_id>', views.add_sensor, name='add_sensor'),
    path('delete_sensor/<str:pk>', views.delete_sensor, name='delete_sensor'),
    path('edit_sensor/<str:pk>/<str:node_id>', views.edit_sensor, name='edit_sensor'),
    # path('background_view/<int:pk>', views.background_view, name='background_view'),
    path('live_data_tabular', views.live_data_tabular, name='live_data_tabular'),
    # path('background_data', views.background_data, name='background_data'),
    path('fetch_mine_ajax', views.fetch_mine_ajax, name='fetch_mine_ajax'),
    # path('fetch_sensor_values_ajax_p', views.fetch_sensor_values_ajax_p, name='fetch_sensor_values_ajax_p'),
    path('fetch_sensor_values_ajax_h', views.fetch_sensor_values_ajax_h, name='fetch_sensor_values_ajax_h'),
    path('fetch_sensor_values', views.fetch_sensor_values, name='fetch_sensor_values'),
    path('live_data_graph', views.live_data_graph, name='live_data_graph'),
    path('iframe_live_data/<int:mine_id>/<int:node_id>/<int:sensor_id>', views.iframe_live_data,
         name='iframe_live_data'),
    path('fetch_sensor_ajax', views.fetch_sensor_ajax, name='fetch_sensor_ajax'),
    path('fetch_sensors_list', views.fetch_sensors_list, name='fetch_sensors_list'),
    path('fetch_sensor_values_ajax', views.fetch_sensor_values_ajax, name='fetch_sensor_values_ajax'),
    path('report_fetch_sensor_values_ajax', views.report_fetch_sensor_values_ajax,
         name='report_fetch_sensor_values_ajax'),
    path('avg_report_fetch_sensor_values_ajax', views.avg_report_fetch_sensor_values_ajax,
         name='avg_report_fetch_sensor_values_ajax'),
    path('report_fetch_node_values_ajax', views.report_fetch_node_values_ajax, name='report_fetch_node_values_ajax'),

    path('fetch_sensor_ajax_sensor', views.fetch_sensor_ajax_sensor, name='fetch_sensor_ajax_sensor'),
    path('fetch_sensor_values_all_ajax', views.fetch_sensor_values_all_ajax, name='fetch_sensor_values_all_ajax'),

    path('sensor_wise_node', views.sensor_wise_node, name='sensor_wise_node'),
    path('sensor_wise_node_header', views.sensor_wise_node_header, name='sensor_wise_node_header'),
    path('live_map', views.live_map, name='live_map'),
    path('report_table', views.report_table, name='report_table'),  # new
    path('report_graph', views.report_graph, name='report_graph'),  # new
    path('avg_report_table', views.avg_report_table, name='avg_report_table'),

    path('fetch_map_ajax', views.fetch_map_ajax, name='fetch_map_ajax'),
    path('sensor_wise_popup', views.sensor_wise_popup, name='sensor_wise_popup'),
    path('fetch_sensor_values_ajax_sensor_table', views.fetch_sensor_values_ajax_sensor_table,
         name='fetch_sensor_values_ajax_sensor_table'),
    path('fetch_sensor_values_ajax_sensor_body', views.fetch_sensor_values_ajax_sensor_body,
         name='fetch_sensor_values_ajax_sensor_body'),
    path('fetch_map_image', views.fetch_map_image, name="fetch_map_image"),
    path('node_sensor_ajax', views.node_sensor_ajax, name='node_sensor_ajax'),
    path('node_sensor_data_ajax', views.node_sensor_data_ajax, name='node_sensor_data_ajax'),

    path('start_save_sensor/<int:sensor_id>', views.start_save_sensor, name="start_save_sensor"),
    path('start_save_multiple_sensor/<int:mine_id>/<int:node_id>', views.start_save_multiple_sensor,
         name="start_save_multiple_sensor"),

]

sensor/forms.py
from django import forms
from .models import Node, Sensor_Node
from employee.models import MineDetails

class NodeForm(forms.ModelForm):

    mine_id=forms.ModelChoiceField(queryset=MineDetails.objects.all(),widget=forms.Select(attrs={'class': 'form-control', }))
    node_id = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: N001)'
    }))
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Name (Ex: Node1)'
    }))
    location = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Location (Ex: Near Pillar 17)'
    }))
    # ip_add= forms.CharField(max_length=200, widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'IP1 (Ex: 192.168.1.1)'
    # }))
    x_axis = forms.FloatField(widget=forms.TextInput(attrs={
        'class': 'form-control'
        # 'placeholder': 'X Axis (Ex: 17)'
    }))
    y_axis = forms.FloatField(widget=forms.TextInput(attrs={
        'class': 'form-control'
        # 'placeholder': 'Y Axis (Ex: 18)'
    }))
    photo1 = forms.ImageField()
    photo2 = forms.ImageField()
    description = forms.CharField(max_length=200, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description (Ex: )'
    }))

    class Meta():
        model = Node
        fields = ['mine_id', 'node_id', 'name', 'location', 'x_axis', 'y_axis', 'photo1', 'photo2', 'description',
                  'isgoaf']


class Sensor_NodeForm(forms.ModelForm):
    sensor_id = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: S001)'
    }))
    ip_add = forms.GenericIPAddressField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'IP (Ex: 192.168.1.1)'
    }))
    GAS_SENSOR_CHOICES = (
        ('CO', 'CO'),
        ('CO2', 'CO2'),
        ('CH4', 'CH4'),
        ('O2', 'O2'),
        ('H2', 'H2'),
        ('N2', 'N2'),
        ('C2H4', 'C2H4')
    )
    sensor_name = forms.CharField(max_length=200, widget=forms.Select(choices=GAS_SENSOR_CHOICES,attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: CH2)',
        'style': 'text-transform:uppercase;'
    }))
    sensor_unit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex:  ppm)'
    }))
    sensor_threshold_limit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: 100 ppm)'
    }))
    level_1_warning_unit = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ex: 5 ',
        'data-toggle': "tooltip",
        'data-placement': "right",
        'title': "Tips: Conversion should be 5"

    }))
    level_2_warning_unit = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ex: 8 ',
        'data-toggle': "tooltip",
        'data-placement': "right",
        'title': "Tips: Conversion should be 8"
    }))
    level_3_warning_unit = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ex: 10 ',
        'data-toggle': "tooltip",
        'data-placement': "right",
        'title': "Tips: Conversion should be 10"
    }))
    level_1_color = forms.CharField(required=False, initial='#ADFF2F',
                                    widget=forms.TextInput(attrs={'class': "jscolor  form-control", "id": "color1","value":"ADFF2F"}))
    level_2_color = forms.CharField(required=False, initial='#FFA500',
                                    widget=forms.TextInput(attrs={'class': "jscolor form-control", "id": "color2","value":"FFA500"}))
    level_3_color = forms.CharField(required=False, initial='#FF0000',
                                    widget=forms.TextInput(attrs={'class': "jscolor  form-control", "id": "color3","value":"FF0000"}))
    level_1_msg = forms.CharField(required=False,
                                  initial='Environment Condition:First Stage Warning Message , Please be Careful.',
                                  widget=forms.TextInput(attrs={'class': 'form-control', }))
    level_2_msg = forms.CharField(required=False,
                                  initial='Environment Condition:Second Stage Warning Message , Please be alert situation is not good.',
                                  widget=forms.TextInput(attrs={'class': 'form-control', }))
    level_3_msg = forms.CharField(required=False,
                                  initial='Environment Condition:Third Stage Warning Message , Please  leave the underground',
                                  widget=forms.TextInput(attrs={'class': 'form-control', }))

    interval_time = forms.CharField(initial=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '30 Sec '
    }))
    description = forms.CharField(required=False,
                                  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'if any info'}))

    level_1_audio = forms.FileField(required=False)
    level_2_audio = forms.FileField(required=False)
    level_3_audio = forms.FileField(required=False)

    CHOICES = [('text2voice', 'Text message to voice convert'),
               ('mp3only', 'Play uploaded mp3 only')]
    audio_play_type = forms.ChoiceField(choices=CHOICES, initial='text2voice',
                                        widget=forms.RadioSelect(attrs={"class": "audio_play_type"}))

    description = forms.CharField(max_length=200, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description (Ex: )'
    }))


    class Meta():
        model = Sensor_Node
        fields = ['ip_add', 'sensor_id', 'sensor_name', 'sensor_unit', 'sensor_threshold_limit', 'level_1_warning_unit',
                  'level_2_warning_unit',
                  'level_3_warning_unit', 'level_1_color', 'level_2_color', 'level_3_color', 'level_1_msg', 'level_2_msg',
                  'level_3_msg', 'interval_time', 'level_1_audio', 'level_2_audio',
                  'level_3_audio', 'audio_play_type',
                  'description']


# class SensorForm(forms.ModelForm):
#     sensorid = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Sensor ID (Ex: S001)'
#     }))
#     sensorname = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Sensor Name (Ex: CH4 )'
#     }))
#     minrange = forms.IntegerField( widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Min Range (Ex: 25)'
#     }))
#     maxrange = forms.IntegerField( widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Max Range (Ex: 56)'
#     }))
#     sensorunit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Sensor Unit (Ex: ppm)'
#     }))
#     thresholdlimit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Threshold Limit (Ex: 45)'
#     }))
#     greenlevel = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Green Level (Ex: 25)'
#     }))
#     yellowlevel = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Yellow Level (Ex: 30)'
#     }))
#     redlevel = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Red Level (Ex: 52)'
#     }))
#     photo = forms.ImageField()
#
#     class Meta:
#         model = Sensor
#         fields = ['id','sensorid','sensorname','minrange','maxrange','sensorunit','thresholdlimit','greenlevel','yellowlevel','redlevel','photo']

# class WirelessForm(forms.ModelForm):
#     ipaddress = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'IP Address (Ex: 192.168.0.204)'
#     }))
#     name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Name (Ex: WN001)'
#     }))
#
#     class Meta:
#         model = Wireless
#         fields = ['id', 'ipaddress', 'name']


class gasModel_autoForm(forms.Form):
    CH4 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 0.75'}))
    CO = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 200'}))
    CO2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 30.5'}))
    O2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 21'}))
    H2S = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 10'}))
    NO2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 10'}))
    SO2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 5'}))
    H2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 0.055'}))
    He = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 0.0524'}))

sensor/templates/sensor/manage_sensor.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <section class="col-md-12">
{#                <h1 class="page-header">Manage wireless Sensor</h1>#}
                 <h3 class="page-header"><b>ENVIRONMENT MONITORING : {{ action }} SENSOR UNDER</b>
                   (<span style="color:Tomato;">{{ mine_name }}</span> /
                    <span style="color:Tomato;">{{ node_name }}</span>)
                </h3>
                <div class="row text-center">
                    <div class="col-md-12">
                        <a class="btn btn-primary" href="{% url 'sensor:add_sensor' mine|encrypt node_id|encrypt %}">Add Sensor</a>
                    </div>
                </div>
        <hr>
        <!-- Table content -->
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table table-bordered" id="content">
                        <thead>
                        <tr>
                            <th class="text-center">SL No</th>
                            <th class="text-center">Mine name</th>
                            <th class="text-center">Sensor Id</th>
                            <th class="text-center">Sensor Name</th>
                            <th class="text-center">IP Address</th>
                            <th class="text-center">Sensor unit</th>
                            <th class="text-center">Threshold Vlaue</th>
                            <th class="text-center">Sensor data acquisition</th>
                            <th class="text-center">Edit</th>
                            <th class="text-center">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for wireless in result %}
                            <tr>
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-center">{{ wireless.mine_name }}</td>
                                <td class="text-center">{{ wireless.sensor_id }}</td>
                                <td class="text-center">{{ wireless.sensor_name }}</td>
                                <td class="text-center">{{ wireless.ip }}</td>
                                <td class="text-center">{{ wireless.unit }}</td>
                                <td class="text-center">{{ wireless.thresholdlimit }}</td>
                                <td class="text-center"><input {% if wireless.background %}checked {% endif %}
                                                                       data-url="{% url 'sensor:start_save_sensor' wireless.id %}"
                                                                       id="isAcquire{{ wireless.id }}"
                                                                       data-val="{{ wireless.id }}" class="DataAcquisition"
                                                                       type="checkbox"
                                                                       data-toggle="toggle" data-on="On"
                                                                       data-off="off" data-onstyle="success"
                                                                       data-offstyle="danger"></td>
                                <td class="text-center">
                                    <a href="{% url 'sensor:edit_sensor' wireless.id|encrypt wireless.node_id|encrypt %}"
                                        title="Edit Node.">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>

                                </td>
                                <td class="text-center"><a href="#" class="delete"
                                                           data-url="{% url 'sensor:delete_sensor' wireless.id|encrypt %}"
                                                           title="Delete Node."><span
                                        class="glyphicon glyphicon-trash"></span></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!--end Table content -->
        </section>
    </div>
    </div>
    <script>
     $(document).ready(function () {
          $(document.body).on("click", ".delete", function () {
            $("#sureDelete").attr("href", $(this).data('url'));
            $('#update_info').modal('show');

        });

     $('.DataAcquisition').change(function () {
                let isAcquire=this.id;
                let action=$('#'+isAcquire).prop("checked");
                $.ajax({
                    type: "post",
                    url: $(this).data('url'),
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        'action':action
                    },
                    success: function (json) {
                        if(json.hasOwnProperty("error")){
                            $('#'+isAcquire).bootstrapToggle('off');
                        }
                    },
                    error: function () {
                         $('#'+isAcquire).bootstrapToggle('off');
                        console.log("something is not right.please contact admin - 1");
                    }
                });
                {#console.log($(this).data('val'), $(this).prop('checked'));#}
            });


           });

    </script>

{% endblock %}

sensor/templates/sensor/test1.html
<html>
<head>
    <title>Wireless Node location</title>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'image/csir_logo.ico' %}" type="image/icon type">
    <link rel="shortcut icon" href="{% static 'image/favicon.ico' %}" type="image/icon type">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static '/css/KBmapmarkers.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <style>
        * {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}

body {
  padding: 0;
  margin: 0;
}

#notfound {
  position: relative;
  height: 100vh;
}

#notfound .notfound {
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound {
  max-width: 520px;
  width: 100%;
  line-height: 1.4;
  text-align: center;
}

.notfound .notfound-404 {
  position: relative;
  height: 200px;
  margin: 0px auto 20px;
  z-index: -1;
}

.notfound .notfound-404 h1 {
  font-family: 'Montserrat', sans-serif;
  font-size: 236px;
  font-weight: 200;
  margin: 0px;
  color: #211b19;
  text-transform: uppercase;
  position: absolute;
  left: 50%;
  top: 50%;
  -webkit-transform: translate(-50%, -50%);
      -ms-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
}

.notfound .notfound-404 h2 {
  font-family: 'Montserrat', sans-serif;
  font-size: 28px;
  font-weight: 400;
  text-transform: uppercase;
  color: #211b19;
  background: #fff;
  padding: 10px 5px;
  margin: auto;
  display: inline-block;
  position: absolute;
  bottom: 0px;
  left: 0;
  right: 0;
}

.notfound a {
  font-family: 'Montserrat', sans-serif;
  display: inline-block;
  font-weight: 700;
  text-decoration: none;
  color: #fff;
  text-transform: uppercase;
  padding: 13px 23px;
  background: #ff6300;
  font-size: 18px;
  -webkit-transition: 0.2s all;
  transition: 0.2s all;
}

.notfound a:hover {
  color: #ff6300;
  background: #211b19;
}

@media only screen and (max-width: 767px) {
  .notfound .notfound-404 h1 {
    font-size: 148px;
  }
}

@media only screen and (max-width: 480px) {
  .notfound .notfound-404 {
    height: 148px;
    margin: 0px auto 10px;
  }
  .notfound .notfound-404 h1 {
    font-size: 86px;
  }
  .notfound .notfound-404 h2 {
    font-size: 16px;
  }
  .notfound a {
    padding: 7px 15px;
    font-size: 14px;
  }
}

    </style>
</head>
<body>
<div class="container">
    <input hidden value="{{ mine_id }}" id="mine_id" data-url="{% url 'Strata:fetch_map_image' %}">
    <input hidden value="{{ x }}" id="x_axis">
    <input hidden value="{{ y }}" id="y_axis">
    <input hidden value="{{ node_name }}" id="node">
    <input hidden value="{{ content }}" id="content">
    <input hidden value="{{ location }}" id="location">


    {% if not error %}
      <section class="KBmap" id="KBtestmap"/>
        {% else %}
        <div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - Image could not be loaded</h2>
			</div>
			<a href="#">Go TO Homepage</a>
		</div>
	</div>
    {% endif %}
</div>

<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'datetime/js/moment.js' %}"></script>
<script src="{% static 'datetime/js/moment-with-locales.js' %}"></script>
<script src="{% static 'datetime/js/collapse.js' %}"></script>
<script src="{% static 'datetime/js/transition.min.js' %}"></script>
<script src="{% static 'datetime/js/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'js/plotly-latest.min.js' %}"></script>
<script src="{% static 'js/customJS.js' %}"></script>
<script src="{% static 'js/KBmapmarkers.js' %}"></script>
<script src="{% static 'js/KBmapmarkersCords.js' %}"></script>
<script>
    $(document).ready(function () {
        setImageData($("#mine_id").val());

        function setImageData(mine_id) {
            url = $("#mine_id").data('url');

            $.ajax({
                type: "get",
                url: url,
                data: {
                    'id': mine_id
                },
                success: function (data) {
                    tempData = data;
                    CreateKBtestMap(data.result.image_url);
                },
                error: function () {
                    console.log("something is not right.please contact admin - 1");
                }
            });
        }
        function CreateKBtestMap(data) {
            var img = data;
            if (addedKBmaps.length > 0) {
                addedKBmaps.pop();
                $('.KBmap__mapContainer').remove();
            }

            if (img) {
                createKBmap('KBtestmap', '/media/' + img);
                var icon = "/static/image/router.svg";
                KBtestmap.addMarker(icon, $('#x_axis').val(), $('#y_axis').val(), 'Test');
                KBtestmap.mapMarkers["Test"].addModal('<b>' + $('#node').val() + '</b>', '<b>Location:</b> ' + $('#location').val() + '<br>' + $('#content').val());

                KBtestmap.showAllMapMarkers();
            } else {
                $("#map").css("");
                $("#map").html("No Mine map(blue print) is added in this mine.please add it.");
            }
        }
    });
</script>
</body>
</html>