SMS/urls.py
from django.urls import path

from SMS import views

app_name = 'sms'
urlpatterns = [
    path('', views.index, name='index'),
    # path('update_news/<int:pk>',views.update_news,name='update_news'),
    # path('get_news_ajax/',views.get_news_ajax,name='get_news_ajax'),
    # path('update_news_download_number_ajax/',views.update_news_download_number_ajax,name='update_news_download_number_ajax'),
    # path('delete_news_ajax/',views.delete_news_ajax,name='delete_news_ajax'),
]

apps/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.models import User
from django.urls import include, path
from django.contrib import admin


from theme import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.home),
    path('base_layout',views.base_layout,name='base_layout'),

    path('employee/',include('employee.urls',namespace='employee')),
    path('MinersTracking/',include('MinersTracking.urls',namespace='MinersTracking')),
    path('FireExp/',include('FireExp.urls',namespace='FireExp')),
    path('Controlling/',include('Controlling.urls',namespace='Controlling')),
    path('DGMS_Forms/',include('DGMS_Forms.urls',namespace='DGMS_Forms')),
    path('Strata/',include('Strata.urls',namespace='Strata')),
    path('theme/',include('theme.urls',namespace='theme')),


    path('accounts/', include('accounts.urls')),
    path('snippets/', include('snippets.urls')),
    path('gasmonitoring/', include('gasmonitoring.urls', namespace='gasmonitoring')),
    path('temp_monitoring/', include('temp_monitoring.urls', namespace='temp_monitoring')),
    path('gasmonitoring_wifi/', include('gasmonitoring_wifi.urls', namespace='gasmonitoring_wifi')),
    path('inventory_management/', include('inventory_management.urls', namespace='inventory_management')),

    path('attendance/', include('attendance.urls', namespace='attendance')),
    path('Training_Rescue_Accident/', include('Training_Rescue_Accident.urls', namespace='Training_Rescue_Accident')),
    path('ProductionMonitoring/', include('ProductionMonitoring.urls',namespace='ProductionMonitoring')),
    path('sensor/', include('sensor.urls', namespace='sensor')),### prasanjit dey(gas monitoring)
    path('water_level_monitoring/', include('water_level_monitoring.urls', namespace='water_level_monitoring')),### SS MISHRA(water monitoring)
    # path('tags_input/', include('tags_input.urls', namespace='tags_input')),
    path('sms/', include('SMS.urls', namespace='sms')),
    path('news/', include('news.urls', namespace='news')),
    path('emails/', include('emails.urls', namespace='emails')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('wm_test/', include('wm_test.urls', namespace='weather_monitoring')),
    path('setting/', include('setting.urls', namespace='setting')),
    path('Slope/', include('Slope.urls', namespace='Slope')),
    path('safety/', include('safety.urls', namespace='safety')),
    # path('',include('pwa.urls')),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                      # For django versions before 2.0:
                      # url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = 'apps.views.error_404_view'

sensor/urls.py
from django.urls import path

# from sensor import views
from . import views

# from arduino import views
app_name = 'sensor'

urlpatterns = [
    path('node_manage/', views.node_manage, name='node_manage'),
    path('node_add', views.node_add, name='node_add'),
    path('node_edit/<str:pk>', views.node_edit, name='node_edit'),
    path('node_delete/', views.node_delete, name='node_delete'),
    path('ellicots/<str:pk>', views.ellicots, name='ellicots'),
    path('line_chart_ratio_graph/<str:pk>', views.line_chart_ratio_graph, name='line_chart_ratio_graph'),
    path('line_chart_ratio_graph_ajax', views.line_chart_ratio_graph_ajax, name='line_chart_ratio_graph_ajax'),

    path('youngs_ratio_graph/<str:pk>', views.youngs_ratio_graph, name='youngs_ratio_graph'),
    path('youngs_ratio_graph_ajax', views.youngs_ratio_graph_ajax, name='youngs_ratio_graph_ajax'),
    path('ellicots_ajax', views.ellicots_ajax, name='ellicots_ajax'),

    path('locate_node/<str:mine_id>/<str:node_id>', views.locate_node, name='locate_node'),

    path('fetch_node_ajax', views.fetch_node_ajax, name='fetch_node_ajax'),

    path('manage_sensor/<str:mine_id>/<str:node_id>', views.manage_sensor, name='manage_sensor'),

    path('add_sensor/<str:mine_id>/<str:node_id>', views.add_sensor, name='add_sensor'),
    path('delete_sensor/<str:pk>', views.delete_sensor, name='delete_sensor'),
    path('edit_sensor/<str:pk>/<str:node_id>', views.edit_sensor, name='edit_sensor'),
    # path('background_view/<int:pk>', views.background_view, name='background_view'),
    path('live_data_tabular', views.live_data_tabular, name='live_data_tabular'),
    # path('background_data', views.background_data, name='background_data'),
    path('fetch_mine_ajax', views.fetch_mine_ajax, name='fetch_mine_ajax'),
    # path('fetch_sensor_values_ajax_p', views.fetch_sensor_values_ajax_p, name='fetch_sensor_values_ajax_p'),
    path('fetch_sensor_values_ajax_h', views.fetch_sensor_values_ajax_h, name='fetch_sensor_values_ajax_h'),
    path('fetch_sensor_values', views.fetch_sensor_values, name='fetch_sensor_values'),
    path('live_data_graph', views.live_data_graph, name='live_data_graph'),
    path('iframe_live_data/<int:mine_id>/<int:node_id>/<int:sensor_id>', views.iframe_live_data,
         name='iframe_live_data'),
    path('fetch_sensor_ajax', views.fetch_sensor_ajax, name='fetch_sensor_ajax'),
    path('fetch_sensors_list', views.fetch_sensors_list, name='fetch_sensors_list'),
    path('fetch_sensor_values_ajax', views.fetch_sensor_values_ajax, name='fetch_sensor_values_ajax'),
    path('report_fetch_sensor_values_ajax', views.report_fetch_sensor_values_ajax,
         name='report_fetch_sensor_values_ajax'),
    path('avg_report_fetch_sensor_values_ajax', views.avg_report_fetch_sensor_values_ajax,
         name='avg_report_fetch_sensor_values_ajax'),
    path('report_fetch_node_values_ajax', views.report_fetch_node_values_ajax, name='report_fetch_node_values_ajax'),

    path('fetch_sensor_ajax_sensor', views.fetch_sensor_ajax_sensor, name='fetch_sensor_ajax_sensor'),
    path('fetch_sensor_values_all_ajax', views.fetch_sensor_values_all_ajax, name='fetch_sensor_values_all_ajax'),

    path('sensor_wise_node', views.sensor_wise_node, name='sensor_wise_node'),
    path('sensor_wise_node_header', views.sensor_wise_node_header, name='sensor_wise_node_header'),
    path('live_map', views.live_map, name='live_map'),
    path('report_table', views.report_table, name='report_table'),  # new
    path('report_graph', views.report_graph, name='report_graph'),  # new
    path('avg_report_table', views.avg_report_table, name='avg_report_table'),

    path('fetch_map_ajax', views.fetch_map_ajax, name='fetch_map_ajax'),
    path('sensor_wise_popup', views.sensor_wise_popup, name='sensor_wise_popup'),
    path('fetch_sensor_values_ajax_sensor_table', views.fetch_sensor_values_ajax_sensor_table,
         name='fetch_sensor_values_ajax_sensor_table'),
    path('fetch_sensor_values_ajax_sensor_body', views.fetch_sensor_values_ajax_sensor_body,
         name='fetch_sensor_values_ajax_sensor_body'),
    path('fetch_map_image', views.fetch_map_image, name="fetch_map_image"),
    path('node_sensor_ajax', views.node_sensor_ajax, name='node_sensor_ajax'),
    path('node_sensor_data_ajax', views.node_sensor_data_ajax, name='node_sensor_data_ajax'),

    path('start_save_sensor/<int:sensor_id>', views.start_save_sensor, name="start_save_sensor"),
    path('start_save_multiple_sensor/<int:mine_id>/<int:node_id>', views.start_save_multiple_sensor,
         name="start_save_multiple_sensor"),

]

sensor/forms.py
from django import forms
from .models import Node, Sensor_Node
from employee.models import MineDetails

class NodeForm(forms.ModelForm):

    mine_id=forms.ModelChoiceField(queryset=MineDetails.objects.all(),widget=forms.Select(attrs={'class': 'form-control', }))
    node_id = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: N001)'
    }))
    name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Name (Ex: Node1)'
    }))
    location = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Location (Ex: Near Pillar 17)'
    }))
    # ip_add= forms.CharField(max_length=200, widget=forms.TextInput(attrs={
    #     'class': 'form-control',
    #     'placeholder': 'IP1 (Ex: 192.168.1.1)'
    # }))
    x_axis = forms.FloatField(widget=forms.TextInput(attrs={
        'class': 'form-control'
        # 'placeholder': 'X Axis (Ex: 17)'
    }))
    y_axis = forms.FloatField(widget=forms.TextInput(attrs={
        'class': 'form-control'
        # 'placeholder': 'Y Axis (Ex: 18)'
    }))
    photo1 = forms.ImageField()
    photo2 = forms.ImageField()
    description = forms.CharField(max_length=200, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description (Ex: )'
    }))

    class Meta():
        model = Node
        fields = ['mine_id', 'node_id', 'name', 'location', 'x_axis', 'y_axis', 'photo1', 'photo2', 'description',
                  'isgoaf']


class Sensor_NodeForm(forms.ModelForm):
    sensor_id = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: S001)'
    }))
    ip_add = forms.GenericIPAddressField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'IP (Ex: 192.168.1.1)'
    }))
    GAS_SENSOR_CHOICES = (
        ('CO', 'CO'),
        ('CO2', 'CO2'),
        ('CH4', 'CH4'),
        ('O2', 'O2'),
        ('H2', 'H2'),
        ('N2', 'N2'),
        ('C2H4', 'C2H4')
    )
    sensor_name = forms.CharField(max_length=200, widget=forms.Select(choices=GAS_SENSOR_CHOICES,attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: CH2)',
        'style': 'text-transform:uppercase;'
    }))
    sensor_unit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex:  ppm)'
    }))
    sensor_threshold_limit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Node ID (Ex: 100 ppm)'
    }))
    level_1_warning_unit = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ex: 5 ',
        'data-toggle': "tooltip",
        'data-placement': "right",
        'title': "Tips: Conversion should be 5"

    }))
    level_2_warning_unit = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ex: 8 ',
        'data-toggle': "tooltip",
        'data-placement': "right",
        'title': "Tips: Conversion should be 8"
    }))
    level_3_warning_unit = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'ex: 10 ',
        'data-toggle': "tooltip",
        'data-placement': "right",
        'title': "Tips: Conversion should be 10"
    }))
    level_1_color = forms.CharField(required=False, initial='#ADFF2F',
                                    widget=forms.TextInput(attrs={'class': "jscolor  form-control", "id": "color1","value":"ADFF2F"}))
    level_2_color = forms.CharField(required=False, initial='#FFA500',
                                    widget=forms.TextInput(attrs={'class': "jscolor form-control", "id": "color2","value":"FFA500"}))
    level_3_color = forms.CharField(required=False, initial='#FF0000',
                                    widget=forms.TextInput(attrs={'class': "jscolor  form-control", "id": "color3","value":"FF0000"}))
    level_1_msg = forms.CharField(required=False,
                                  initial='Environment Condition:First Stage Warning Message , Please be Careful.',
                                  widget=forms.TextInput(attrs={'class': 'form-control', }))
    level_2_msg = forms.CharField(required=False,
                                  initial='Environment Condition:Second Stage Warning Message , Please be alert situation is not good.',
                                  widget=forms.TextInput(attrs={'class': 'form-control', }))
    level_3_msg = forms.CharField(required=False,
                                  initial='Environment Condition:Third Stage Warning Message , Please  leave the underground',
                                  widget=forms.TextInput(attrs={'class': 'form-control', }))

    interval_time = forms.CharField(initial=30, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': '30 Sec '
    }))
    description = forms.CharField(required=False,
                                  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'if any info'}))

    level_1_audio = forms.FileField(required=False)
    level_2_audio = forms.FileField(required=False)
    level_3_audio = forms.FileField(required=False)

    CHOICES = [('text2voice', 'Text message to voice convert'),
               ('mp3only', 'Play uploaded mp3 only')]
    audio_play_type = forms.ChoiceField(choices=CHOICES, initial='text2voice',
                                        widget=forms.RadioSelect(attrs={"class": "audio_play_type"}))

    description = forms.CharField(max_length=200, widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Description (Ex: )'
    }))


    class Meta():
        model = Sensor_Node
        fields = ['ip_add', 'sensor_id', 'sensor_name', 'sensor_unit', 'sensor_threshold_limit', 'level_1_warning_unit',
                  'level_2_warning_unit',
                  'level_3_warning_unit', 'level_1_color', 'level_2_color', 'level_3_color', 'level_1_msg', 'level_2_msg',
                  'level_3_msg', 'interval_time', 'level_1_audio', 'level_2_audio',
                  'level_3_audio', 'audio_play_type',
                  'description']


# class SensorForm(forms.ModelForm):
#     sensorid = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Sensor ID (Ex: S001)'
#     }))
#     sensorname = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Sensor Name (Ex: CH4 )'
#     }))
#     minrange = forms.IntegerField( widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Min Range (Ex: 25)'
#     }))
#     maxrange = forms.IntegerField( widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Max Range (Ex: 56)'
#     }))
#     sensorunit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Sensor Unit (Ex: ppm)'
#     }))
#     thresholdlimit = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Threshold Limit (Ex: 45)'
#     }))
#     greenlevel = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Green Level (Ex: 25)'
#     }))
#     yellowlevel = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Yellow Level (Ex: 30)'
#     }))
#     redlevel = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Red Level (Ex: 52)'
#     }))
#     photo = forms.ImageField()
#
#     class Meta:
#         model = Sensor
#         fields = ['id','sensorid','sensorname','minrange','maxrange','sensorunit','thresholdlimit','greenlevel','yellowlevel','redlevel','photo']

# class WirelessForm(forms.ModelForm):
#     ipaddress = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'IP Address (Ex: 192.168.0.204)'
#     }))
#     name = forms.CharField(max_length=200, widget=forms.TextInput(attrs={
#         'class': 'form-control',
#         'placeholder': 'Name (Ex: WN001)'
#     }))
#
#     class Meta:
#         model = Wireless
#         fields = ['id', 'ipaddress', 'name']


class gasModel_autoForm(forms.Form):
    CH4 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 0.75'}))
    CO = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 200'}))
    CO2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 30.5'}))
    O2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 21'}))
    H2S = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 10'}))
    NO2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 10'}))
    SO2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 5'}))
    H2 = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 0.055'}))
    He = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Eg. 0.0524'}))

sensor/templates/node/node_manage.html
{% extends "base.html" %}

{% block content %}
    {% load staticfiles %}
    <div class="container">
        <section class="col-md-12">
            <h3 class="page-header text-center"><b>Manage Wireless Node</b>
                <small>&nbspHere you can update ,view and delete nodes</small>
            </h3>
            <div class="row text-center">
                <div class="col-md-12">
                    <a class="btn btn-primary" href="{% url 'sensor:node_add' %}">Add Wireless Node</a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive ">
                        <table class="table hover  table-bordered " id="myTable">
                            <thead>
                            <tr>
                                <th>SL No</th>
                                <th>Mine Name</th>
                                <th>Node ID</th>
                                <th>Node Name</th>
                                <th>Node Location</th>
                                <th>X,Y (Axis)</th>
                                <th>Description</th>
                                <th>Is it Goaf?</th>
                                <th>Images</th>
                                <th>Data Aquition</th>
                                <th>Manage Sensor</th>
                                <th>Edit</th>
                                <th>Delete</th>

                            </tr>
                            </thead>
                            <tbody id="RouterList">
                            {% for book in object_list %}


                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ book.mine_id.name }}</td>
                                    <td>{{ book.node_id }}</td>
                                    <td>{{ book.name }}</td>
                                    <td>{{ book.location }}</td>
                                    <td>{{ book.x_axis }},{{ book.y_axis }}</td>
                                    <td class="more">{{ book.description }}</td>
                                    <td class="text-center"><h4>
                                        {% if book.isgoaf == True %}
                                            <span class="label label-success">Yes</span>
                                        {% else %}
                                            <span class="label label-danger">No</span>
                                        {% endif %}
                                    </h4>
                                    </td>
                                    <td class="text-center"><img data-toggle="tooltip" data-original-title="Image 1" class="image image-responsive"
                                             src="/media/{{ book.photo1 }}"
                                             height="60" width="60"/>
                                        <img data-toggle="tooltip" data-original-title="Image 2" class="image image-responsive"
                                             src="/media/{{ book.photo2 }}"
                                             height="60" width="60"/>
                                    </td>

                                    <td class="text-center"><input
                                            {% if background|lookup:book.id %}checked {% endif %}
                                            data-url="{% url 'sensor:start_save_multiple_sensor' book.mine_id_id book.id %}"
                                            id="isAcquire{{ book.id }}"
                                            data-val="{{ book.id }}" class="DataAcquisition"
                                            type="checkbox"
                                            data-toggle="toggle" data-on="On"
                                            data-off="off" data-onstyle="success"
                                            data-offstyle="danger"></td>

                                    <td class="text-center">
                                        <a href="{% url 'sensor:manage_sensor' book.mine_id.id|encrypt book.id|encrypt %}"
                                           class="manageSensor"
                                           data-url="{% url 'sensor:manage_sensor' book.mine_id.id book.id %}" 0
                                           data-toggle="tooltip" data-original-title="Manage Sensor">
                                            <span class="glyphicon glyphicon-plus"></span>
                                        </a>
                                        <br>
                                        <br>
                                        {% if book.isgoaf %}
                                            <a href="#"
                                               onclick="window.open('{% url 'sensor:ellicots' book.id|encrypt %}', 'Ellicots Graph', 'width=1300, height=900','title=Hello'); return false;"
                                               data-toggle="tooltip" data-original-title="Generate Ellicots Graph.">
                                                <span class="glyphicon glyphicon-picture"></span>
                                            </a>
                                            &nbsp;&nbsp;
                                            <a href="#"
                                               onclick="window.open('{% url 'sensor:line_chart_ratio_graph' book.id|encrypt %}', 'Line Chart Graph', 'width=1300, height=900','title=Hello'); return false;"
                                               data-toggle="tooltip" data-original-title="Line Chart Ratio Graph.">
                                                <span class="glyphicon glyphicon-picture"></span>
                                            </a>
                                            &nbsp;&nbsp;
                                            <a href="#"
                                               onclick="window.open('{% url 'sensor:youngs_ratio_graph' book.id|encrypt %}', 'Youngs Ratio Graph.', 'width=1300, height=900','title=Hello'); return false;"
                                               data-toggle="tooltip" data-original-title="Youngs Ratio Graph.">
                                                <span class="glyphicon glyphicon-picture"></span>
                                            </a>
                                            <br>
                                            <br>

                                        {% endif %}

                                        <a href="{% url 'sensor:locate_node' book.mine_id.id|encrypt book.id|encrypt %}"
                                           onclick="window.open('{% url 'sensor:locate_node' book.mine_id.id|encrypt book.id|encrypt %}', 'Node Location', 'width=1000, height=800','title=Hello'); return false;"
                                           data-toggle="tooltip" data-original-title="Show Node Location">
                                            <span class="glyphicon glyphicon-map-marker"></span>
                                        </a>
                                    </td>

                                    <td class="text-center"><a href="{% url 'sensor:node_edit' book.id|encrypt %}"
                                                               class="editRouter"
                                                               data-url="{% url 'sensor:node_edit' book.id|encrypt %}"
                                                               data-toggle="tooltip" data-original-title="Edit Router."><span
                                            class="glyphicon glyphicon-pencil"></span></a></td>
                                    <td class="text-center"><a href="#" class="delete"
                                                               data-url="{% url 'sensor:node_delete' %}"
                                                               id="{{ book.id }}"
                                                               data-toggle="tooltip" data-original-title="Delete Router."><span
                                            class="glyphicon glyphicon-trash"></span></a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'csv', 'excel',
                    {
                        extend: 'print',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5, 7, 8]
                        }
                    },
                    {
                        extend: 'pdf',
                        exportOptions: {
                            columns: [0, 1, 2, 3, 4, 5, 7, 8]
                        }
                    },
                ],
            });

            toastr.options = {
                "closeButton": false,
                "debug": false,
                "newestOnTop": true,
                "progressBar": false,
                "positionClass": "toast-bottom-full-width",
                "preventDuplicates": true,
                "onclick": null,
                "showDuration": "300",
                "hideDuration": "1000",
                "timeOut": "5000",
                "extendedTimeOut": "1000",
                "showEasing": "swing",
                "hideEasing": "linear",
                "showMethod": "fadeIn",
                "hideMethod": "fadeOut",
            };
            (function Delete_Node() {
                $(document.body).on("click", ".delete", function () {
                    $('#update_info').modal('show');
                    let node_id = $(this).attr('id');
                    let url = $(this).data('url');
                    let Curr = $(this).parents('tr');
                    let datatable = $('#myTable').DataTable();
                    $('#update_info').on('click', '#delete', function (e) {
                        $('#update_info').unbind('click');
                        $('#update_info').modal('hide');
                        $.ajax({
                            type: "post",
                            url: url,
                            data: {
                                csrfmiddlewaretoken: "{{ csrf_token }}",
                                'id': node_id,
                            },
                            success: function (json) {
                                if (json.hasOwnProperty("success")) {
                                    datatable.row(Curr).remove().draw();
                                    toastr.success(json.success);
                                } else {
                                    toastr.error(json.error);
                                }
                            },
                            error: function () {
                                console.log("something is not right.please contact admin - 1");
                            }
                        });
                    });
                });
            })();

            $('.DataAcquisition').change(function () {
                let isAcquire = this.id;
                let action = $('#' + isAcquire).prop("checked");

                console.log('Changed', action);
                $.ajax({
                    type: "post",
                    url: $(this).data('url'),
                    data: {
                        csrfmiddlewaretoken: "{{ csrf_token }}",
                        'action': action
                    },
                    success: function (json) {
                        console.log(json);
                        if (json.hasOwnProperty("error")) {
                            $('#' + isAcquire).bootstrapToggle('off');
                        }
                    },
                    error: function () {
                        $('#' + isAcquire).bootstrapToggle('off');
                        console.log("something is not right.please contact admin - 1");
                    }
                });
                {#console.log($(this).data('val'), $(this).prop('checked'));#}
            });

        });
    </script>
    <style>
        .container {
            width: 1251px;
        }

        .red-tooltip + .tooltip > .tooltip-inner {
            background: none;
        }

        .red-tooltip + .tooltip > .tooltip-arrow {
            border-bottom-color: #fff;
        }


    </style>
{% endblock %}